services:
  - type: web
    name: trinetra-ai
    runtime: node
    rootDir: src/backend_api
    buildCommand: npm install
    startCommand: node SERVER.JS
    plan: free
    envVars:
      - key: PORT
        value: 10000
